// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtWdrfml91qyKOn1b7rxiBuTm-EMjCyk',
    appId: '1:955499126701:web:c162de1f7c378852ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    authDomain: 'facebook-clone-9f92c.firebaseapp.com',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    measurementId: 'G-9X9FQRELYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE_VDMcxzmjK-ZU_DCX2jowGW9u_TApVc',
    appId: '1:955499126701:android:f693a9eb6a3a81fcff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2DLRtmYBcYfOFxxPZXOBl2stF6_NVthM',
    appId: '1:955499126701:ios:45915b0db5c4dec7ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2DLRtmYBcYfOFxxPZXOBl2stF6_NVthM',
    appId: '1:955499126701:ios:45915b0db5c4dec7ff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    iosBundleId: 'com.codehq.facebookClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrtWdrfml91qyKOn1b7rxiBuTm-EMjCyk',
    appId: '1:955499126701:web:08f15665fe683e6aff0b24',
    messagingSenderId: '955499126701',
    projectId: 'facebook-clone-9f92c',
    authDomain: 'facebook-clone-9f92c.firebaseapp.com',
    storageBucket: 'facebook-clone-9f92c.appspot.com',
    measurementId: 'G-BQS8ZN0XK9',
  );
}
